package glavacevic.model;
// Generated Oct 4, 2018 1:15:55 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrdersItems generated by hbm2java
 */
@Entity

public class OrdersItems  implements java.io.Serializable {


     private OrdersItemsId id;
     private int quantity;

    public OrdersItems() {
    }

    public OrdersItems(OrdersItemsId id, int quantity) {
       this.id = id;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="order_id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public OrdersItemsId getId() {
        return this.id;
    }
    
    public void setId(OrdersItemsId id) {
        this.id = id;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


