package glavacevic.model;
// Generated Oct 4, 2018 1:15:55 AM by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.CreationTimestamp;

/**
 * Orders generated by hbm2java
 */
@Entity

public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private Date orderDate;
     private String orderName;
     private String orderEmail;
      @CreationTimestamp
    private Timestamp otvorenoVrijeme;

    public Timestamp getOtvorenoVrijeme() {
        return otvorenoVrijeme;
    }

    public void setOtvorenoVrijeme(Timestamp otvorenoVrijeme) {
        this.otvorenoVrijeme = otvorenoVrijeme;
    }

    public Orders() {
    }

//    public Orders(Date orderDate, String orderName, String orderEmail) {
//       this.orderDate = orderDate;
//       this.orderName = orderName;
//       this.orderEmail = orderEmail;
//    }
   
     @Id 
     @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id", unique=true)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", nullable=false, length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="order_name")
    public String getOrderName() {
        return this.orderName;
    }
    
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    
    @Column(name="order_email")
    public String getOrderEmail() {
        return this.orderEmail;
    }
    
    public void setOrderEmail(String orderEmail) {
        this.orderEmail = orderEmail;
    }

    @Override
    public String toString() {
        return getOrderName();
    }
    


}


