package glavacevic.model;
// Generated Oct 4, 2018 1:15:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity

public class Products  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private String productImage;
     private String productDescription;
     private BigDecimal productPrice;

    public Products() {
    }

	
    public Products(String productName, BigDecimal productPrice) {
        this.productName = productName;
        this.productPrice = productPrice;
    }
    public Products(String productName, String productImage, String productDescription, BigDecimal productPrice) {
       this.productName = productName;
       this.productImage = productImage;
       this.productDescription = productDescription;
       this.productPrice = productPrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="product_image")
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    
   
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    
    @Column(name="product_price", nullable=false, precision=10)
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

 @Override
    public String toString() {
        return getProductName();
    }


}


