/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glavacevic.view;

import glavacevic.controller.ObradaZaposlenik;
import glavacevic.model.Zaposlenik;
import glavacevic.pomocno.EdunovaException;
import glavacevic.pomocno.HibernateUtil;
import java.awt.Color;
import java.awt.Component;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXLabel;
import AppPackage.AnimationClass;
import glavacevic.pomocno.SpremiSliku;
import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MacaZekoMiš
 */
public class ArtistiPanel extends javax.swing.JPanel {

    private Zaposlenik entitet;
    private ObradaZaposlenik obrada;

    /**
     * Creates new form DobarDan
     */
    public ArtistiPanel() {
        initComponents();
        setName("Polaznici");
        obrada = new ObradaZaposlenik();
        error_Ime.setVisible(false);
        error_Prezime.setVisible(false);
        txt_Direktorij2.setVisible(false);
        ucitaj();

    }

    String putanja = System.getProperty("user.dir");
    AnimationClass AC = new AnimationClass();
    AnimationClass AV = new AnimationClass();

    private void ucitaj() {
        DefaultListModel<Zaposlenik> m = new DefaultListModel<>();
        List<Zaposlenik> lista = obrada.getEntiteti(txtUvjet.getText());

        //sortirati po prezimenu
        Collections.sort(lista, new Comparator<Zaposlenik>() {
            public int compare(Zaposlenik o1, Zaposlenik o2) {
                return o1.getPrezime().compareTo(o2.getPrezime());
            }
        });

        lista.forEach((s) -> {
            m.addElement(s);
        });
        lstEntiteti.setModel(m);
        ocistiPolja();
        if (m.getSize() > 0) {
            lstEntiteti.setSelectedIndex(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GradientPanelArtist = new keeptoo.KGradientPanel();
        btn_slika3 = new javax.swing.JButton();
        lbl_img2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUvjet = new javax.swing.JTextField();
        pnlPodatci = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGrupe = new javax.swing.JList();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        error_Ime = new javax.swing.JLabel();
        error_Prezime = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_dot2 = new javax.swing.JLabel();
        okrug2 = new javax.swing.JLabel();
        prbBrisanje = new javax.swing.JProgressBar();
        chkProvjeriEmail = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntiteti = new javax.swing.JList<>();
        info_icon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        adresa_ph = new javax.swing.JLabel();
        oib_ph = new javax.swing.JLabel();
        txtOIB1 = new javax.swing.JTextField();
        txtBrojUgovora = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        ph4 = new javax.swing.JLabel();
        txtNaziv1 = new javax.swing.JTextField();
        ph3 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_Direktorij2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jCombo_zanr = new javax.swing.JComboBox<>();
        btnDodajNovi = new javax.swing.JButton();
        btnPromjena = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        GradientPanelArtist.setkEndColor(new java.awt.Color(0, 0, 0));
        GradientPanelArtist.setkStartColor(new java.awt.Color(102, 102, 102));
        GradientPanelArtist.setOpaque(false);

        btn_slika3.setBackground(new java.awt.Color(69, 202, 255));
        btn_slika3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloud-upload-16.png"))); // NOI18N
        btn_slika3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_slika3ActionPerformed(evt);
            }
        });

        lbl_img2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Male_User_96px_1.png"))); // NOI18N
        lbl_img2.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Search_24px.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        txtUvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUvjetKeyPressed(evt);
            }
        });

        pnlPodatci.setOpaque(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ime");

        jScrollPane3.setViewportView(lstGrupe);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Grupa");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Prezime");

        error_Ime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Cancel_16px_3.png"))); // NOI18N

        error_Prezime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Cancel_16px_3.png"))); // NOI18N
        error_Prezime.setText("lbl");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Email");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(null);

        lbl_dot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dot.png"))); // NOI18N
        jPanel3.add(lbl_dot2);
        lbl_dot2.setBounds(2, 10, 11, 10);

        okrug2.setBackground(new java.awt.Color(255, 255, 255));
        okrug2.setForeground(new java.awt.Color(51, 51, 0));
        okrug2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/withoutdot.png"))); // NOI18N
        jPanel3.add(okrug2);
        okrug2.setBounds(2, 0, 30, 30);

        chkProvjeriEmail.setSelected(true);
        chkProvjeriEmail.setText("Provjeravaj");
        chkProvjeriEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProvjeriEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPodatciLayout = new javax.swing.GroupLayout(pnlPodatci);
        pnlPodatci.setLayout(pnlPodatciLayout);
        pnlPodatciLayout.setHorizontalGroup(
            pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodatciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(jLabel7)
                    .addGroup(pnlPodatciLayout.createSequentialGroup()
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error_Ime, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPodatciLayout.createSequentialGroup()
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error_Prezime, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30)
                    .addGroup(pnlPodatciLayout.createSequentialGroup()
                        .addGroup(pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPodatciLayout.createSequentialGroup()
                                .addGroup(pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prbBrisanje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPodatciLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkProvjeriEmail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pnlPodatciLayout.createSequentialGroup()
                                .addComponent(txtEmail)
                                .addGap(6, 6, 6)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPodatciLayout.setVerticalGroup(
            pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodatciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_Ime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(8, 8, 8)
                .addGroup(pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_Prezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPodatciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkProvjeriEmail))
                .addGap(18, 18, 18)
                .addComponent(prbBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstEntiteti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntitetiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntiteti);

        info_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_More_Info_26px_1.png"))); // NOI18N
        info_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                info_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                info_iconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                info_iconMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        adresa_ph.setForeground(new java.awt.Color(255, 255, 255));
        adresa_ph.setText("Adresa");
        jPanel4.add(adresa_ph);
        adresa_ph.setBounds(120, 140, 110, 20);

        oib_ph.setForeground(new java.awt.Color(255, 255, 255));
        oib_ph.setText("OIB");
        jPanel4.add(oib_ph);
        oib_ph.setBounds(0, 140, 110, 20);
        jPanel4.add(txtOIB1);
        txtOIB1.setBounds(0, 160, 110, 20);
        jPanel4.add(txtBrojUgovora);
        txtBrojUgovora.setBounds(120, 160, 110, 20);
        jPanel4.add(txtNaziv);
        txtNaziv.setBounds(120, 120, 110, 20);

        ph4.setForeground(new java.awt.Color(255, 255, 255));
        ph4.setText("Dopuna");
        jPanel4.add(ph4);
        ph4.setBounds(120, 100, 37, 14);
        jPanel4.add(txtNaziv1);
        txtNaziv1.setBounds(0, 120, 110, 20);

        ph3.setForeground(new java.awt.Color(255, 255, 255));
        ph3.setText("Artist ime");
        jPanel4.add(ph3);
        ph3.setBounds(0, 100, 45, 14);

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Žanr");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(0, 190, 22, 14);

        txt_Direktorij2.setBackground(new java.awt.Color(255, 255, 255));
        txt_Direktorij2.setOpaque(true);
        jPanel4.add(txt_Direktorij2);
        txt_Direktorij2.setBounds(120, 210, 110, 16);

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Direktorij odabrane slike");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(120, 190, 40, 14);

        jCombo_zanr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Techno", "Trance", "Edm", "Rock" }));
        jCombo_zanr.setBorder(null);
        jPanel4.add(jCombo_zanr);
        jCombo_zanr.setBounds(0, 210, 110, 20);

        btnDodajNovi.setText("Dodaj novi");
        btnDodajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNoviActionPerformed(evt);
            }
        });

        btnPromjena.setText("Promjena");
        btnPromjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjenaActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Zaposlenik");

        javax.swing.GroupLayout GradientPanelArtistLayout = new javax.swing.GroupLayout(GradientPanelArtist);
        GradientPanelArtist.setLayout(GradientPanelArtistLayout);
        GradientPanelArtistLayout.setHorizontalGroup(
            GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                                .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPodatci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GradientPanelArtistLayout.createSequentialGroup()
                                .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(info_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPromjena)
                                    .addComponent(btnDodajNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btn_slika3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        GradientPanelArtistLayout.setVerticalGroup(
            GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(info_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                                .addComponent(btnDodajNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPromjena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisi))
                            .addComponent(lbl_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_slika3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GradientPanelArtistLayout.createSequentialGroup()
                                .addGroup(GradientPanelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlPodatci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(241, 241, 241))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GradientPanelArtist, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GradientPanelArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_slika3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_slika3ActionPerformed
        String filename = null;

        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG, GIF, and PNG Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            System.out.println("You chose to open this file: "
                    + file.getName());
            BufferedImage image;
            try {
                image = ImageIO.read(file);

                ImageIO.write(image, "jpg", new File(putanja + file.getName()));
            } catch (IOException ex) {
                Logger.getLogger(SpremiSliku.class.getName()).log(Level.SEVERE, null, ex);
            }

            //       chooser.showOpenDialog(null);
            //       File f = chooser.getSelectedFile();
            filename = file.getAbsolutePath();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img2.getWidth(), lbl_img2.getHeight(), Image.SCALE_SMOOTH));
            lbl_img2.setIcon(imageIcon);
            //            lbl_dirOdabrane.setText(filename);
            txt_Direktorij2.setText(file.getName());

        }
    }//GEN-LAST:event_btn_slika3ActionPerformed

    private void txtUvjetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUvjetKeyPressed
        //        if (evt.getKeyCode() == 10) {
        //            ucitaj();
        //        }
    }//GEN-LAST:event_txtUvjetKeyPressed

    private void lstEntitetiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntitetiValueChanged

        if (evt.getValueIsAdjusting()) {
            return;
        }

        entitet = lstEntiteti.getSelectedValue();
        if (entitet == null) {
            return;
        }
        //btnPredloziBrojUgovora.setEnabled(true);
        ocistiPolja();
        String filename = null;
        txt_Direktorij2.setText(entitet.getDpath());
        txtIme.setText(entitet.getIme());
        txtPrezime.setText(entitet.getPrezime());
       //txtOib.setText(entitet.getOib());
       //txtNaziv.setText(entitet.getNaziv());
        txtEmail.setText(entitet.getEmail());
       //txtBrojUgovora.setText(entitet.getBrojUgovora());
        filename = putanja + entitet.getDpath();
        if (entitet.getDpath() == null || entitet.getDpath().isEmpty()) {
            lbl_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Male_User_96px_1.png")));
        }else{
               ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img2.getWidth(), lbl_img2.getHeight(), Image.SCALE_SMOOTH));
        lbl_img2.setIcon(imageIcon);
          }
    }//GEN-LAST:event_lstEntitetiValueChanged

    private void btnDodajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNoviActionPerformed

        entitet = new Zaposlenik();

        if (!popuniSvojstva()) {
            return;
        }

        ocistiBoje();

        try {

            Zaposlenik novi = obrada.dodaj(entitet);

            ucitaj();

            for (int i = 0; i < lstEntiteti.getModel().getSize(); i++) {
                if (lstEntiteti.getModel().getElementAt(i).getSifra()
                        == novi.getSifra()) {

                    lstEntiteti.setSelectedIndex(i);
                    lstEntiteti.ensureIndexIsVisible(lstEntiteti.getSelectedIndex());
                    break;
                }
            }

        } catch (EdunovaException ex) {

            switch (ex.getPoruka()) {

                case "Ime obavezno":
                    txtIme.setBackground(Color.RED);
//                oznaciBorder(txtIme);
//                        error_Ime.setVisible(true);
//                         error_Prezime.setVisible(false);

                    System.out.println("imeobzv");
                    break;
                case "Prezime obavezno":
                    txtPrezime.setBackground(Color.RED);
//                oznaciBorder(txtPrezime);
                    System.out.println("prez");
//                         error_Prezime.setVisible(true);

            }

            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajNoviActionPerformed

    private boolean popuniSvojstva() {

        entitet.setIme(txtIme.getText());
        entitet.setPrezime(txtPrezime.getText());
        entitet.setOib(txtOIB1.getText());
        entitet.setDpath(txt_Direktorij2.getText());

        if (chkProvjeriEmail.isSelected()
                && !txtEmail.getText().trim().isEmpty()
                && !txtEmail.getText().trim().matches("(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])")) {
            JOptionPane.showMessageDialog(getRootPane(), "Email neispravan");
            return false;
        }
        entitet.setEmail(txtEmail.getText());

//        entitet.setBrojUgovora(txtBrojUgovora.getText());
        return true;
    }

    private void oznaciBorder(JTextField label) {
        label.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000")));
        label.requestFocus();
    }

    private void resetirajBorder(JTextField label) {
        label.setBorder(BorderFactory.createEmptyBorder());
    }


    private void btnPromjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjenaActionPerformed
        entitet = lstEntiteti.getSelectedValue();
        if (entitet == null) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberi smjer");
            return;
        }

        ocistiBoje();

        if (!popuniSvojstva()) {
            return;
        }

        try {
            obrada.promjena(entitet);
            ucitaj();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
        }
    }//GEN-LAST:event_btnPromjenaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        /*
        entitet = lstEntiteti.getSelectedValue();
        if (entitet == null) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberi smjer");
            return;
        }

        obrada.obrisi(entitet);
         */

        if (lstEntiteti.getSelectedValuesList().size() == 0) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite jednog ili više polaznika za brisanje");
            return;
        }

        if (lstEntiteti.getSelectedValuesList().size() == 1) {
            try {
                obrada.obrisi(lstEntiteti.getSelectedValuesList().get(0));
            } catch (Exception ex) {
                HibernateUtil.getSession().clear();
                JOptionPane.showMessageDialog(getRootPane(), "Polaznika "
                        + lstEntiteti.getSelectedValuesList().get(0)
                        + " ne mogu obrisati jer je prijavljen na neku od grupa");
            }
            ucitaj();
        } else {
            new BrisanjePolaznika().start();
        }

    }//GEN-LAST:event_btnObrisiActionPerformed
    Boolean Entered = false;
    double location = 0;

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/withoutdotH.png"));
        okrug2.setIcon(II);
        Entered = true;
        System.err.println("Evo nas " + Entered);

    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        if (Entered) {

            System.err.println("DOBILI SMO osmicu kada smo izašli");
            ImageIcon II = new ImageIcon(getClass().getResource("/images/withoutdot.png"));
            okrug2.setIcon(II);
        }
        if (location == 2) {
            System.err.println("DOBILI SMO dva kada smo izašli");
            ImageIcon IIII = new ImageIcon(getClass().getResource("/images/withoutdotU.png"));

            okrug2.setIcon(IIII);

        }
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed

        if (location != 2) {

            System.err.println("DVICA ko kuča upaljeno je");

            this.repaint();
            this.revalidate();
        } else {
            System.err.println("OSMICA UGAŠENO JE ");

        }

    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased

        AC.jLabelXRight(2, 8, 10, 1, lbl_dot2);

        AC.jLabelXLeft(8, 2, 10, 1, lbl_dot2);

        Point gtz = lbl_dot2.getLocation();

        System.err.println(lbl_dot2.getLocation().getX());
        System.err.println(gtz.getLocation().getX());

        location = gtz.getLocation().getX();

        System.err.println("Double is : " + location);
        if (location == 2) {
            String pozicija = "Dvica";
        }
        if (location == 8) {
            String pozicija = "Osmica";
        }
        if (location == 8 && !Entered) {
            System.err.println("DOBILI SMO OSMICU");
            ImageIcon II = new ImageIcon(getClass().getResource("/images/withoutdot.png"));

            okrug2.setIcon(II);
        }
        if (!Entered && location == 2) {
            System.err.println("DOBILI SMO DVA");
            ImageIcon III = new ImageIcon(getClass().getResource("/images/withoutdotU.png"));

            okrug2.setIcon(III);

        }
        //            pnlSadrzaj.setkTransparentControls(true);
        //        VHATNOT.setVisible(false);
        //
        //                    ImageIcon II = new ImageIcon(getClass().getResource("/images/withoutdot.png"));
        //                    okrug.setIcon(II);
    }//GEN-LAST:event_jPanel3MouseReleased

    private void info_iconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_iconMousePressed
        AC.jTextFieldYUp(160, 0, 10, 1, txtOIB1);
        AC.jLabelYUp(60, 13, 10, 1, oib_ph);
       AC.jTextFieldYUp(120, 30, 10, 1, txtNaziv);
         AC.jTextFieldYUp(120, 30, 10, 1, txtNaziv1);
        AC.jTextFieldYDown(0, 160, 10, 1, txtOIB1);
        AC.jLabelYDown(13, 60, 10, 1, oib_ph);

        AC.jTextFieldYUp(160, 0, 10, 1, txtBrojUgovora);
        AC.jLabelYUp(60, 13, 10, 1, adresa_ph);
        AC.jTextFieldYDown(0, 160, 10, 1, txtBrojUgovora);
        AC.jLabelYDown(13, 60, 10, 1, adresa_ph);
    }//GEN-LAST:event_info_iconMousePressed

    private void info_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_iconMouseEntered
        ImageIcon Info = new ImageIcon(getClass().getResource("/images/icons8_More_Info_26px.png"));
        info_icon.setIcon(Info);
    }//GEN-LAST:event_info_iconMouseEntered

    private void info_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_iconMouseExited
        ImageIcon Info = new ImageIcon(getClass().getResource("/images/icons8_More_Info_26px_1.png"));
        info_icon.setIcon(Info);
    }//GEN-LAST:event_info_iconMouseExited

    private void chkProvjeriEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProvjeriEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProvjeriEmailActionPerformed

    private class BrisanjePolaznika extends Thread {

        public void run() {
            prbBrisanje.setMinimum(0);
            prbBrisanje.setMaximum(lstEntiteti.getSelectedValuesList().size());
            int i = 0;

            for (Zaposlenik e : lstEntiteti.getSelectedValuesList()) {
                prbBrisanje.setValue(++i);
                try {
                    obrada.obrisi(e);
                } catch (Exception ex) {
                    HibernateUtil.getSession().clear();
                    // JOptionPane.showMessageDialog(getRootPane(), "Polaznika " + e + 
                    //         " ne mogu obrisati jer je prijavljen na neku od grupa");
                }
            }
            ucitaj();
        }
    }

    private void ocistiBoje() {
        for (Component c : pnlPodatci.getComponents()) {
            if (c instanceof JTextField) {
                c.setBackground(Color.WHITE);
            }
        }
    }

    private void ocistiPolja() {
        for (Component c : pnlPodatci.getComponents()) {
            if (c instanceof JTextField) {
                ((JTextField) c).setText("");
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel GradientPanelArtist;
    private javax.swing.JLabel adresa_ph;
    private javax.swing.JButton btnDodajNovi;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjena;
    private javax.swing.JButton btn_slika3;
    private javax.swing.JCheckBox chkProvjeriEmail;
    private javax.swing.JLabel error_Ime;
    private javax.swing.JLabel error_Prezime;
    private javax.swing.JLabel info_icon;
    private javax.swing.JComboBox<String> jCombo_zanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_dot2;
    private javax.swing.JLabel lbl_img2;
    protected javax.swing.JList<glavacevic.model.Zaposlenik> lstEntiteti;
    private javax.swing.JList lstGrupe;
    private javax.swing.JLabel oib_ph;
    private javax.swing.JLabel okrug2;
    private javax.swing.JLabel ph3;
    private javax.swing.JLabel ph4;
    private javax.swing.JPanel pnlPodatci;
    private javax.swing.JProgressBar prbBrisanje;
    private javax.swing.JTextField txtBrojUgovora;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtNaziv1;
    private javax.swing.JTextField txtOIB1;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtUvjet;
    private javax.swing.JLabel txt_Direktorij2;
    // End of variables declaration//GEN-END:variables
}
