/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glavacevic.view;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import org.hyperic.sigar.CpuInfo;
import org.hyperic.sigar.NetFlags;
import org.hyperic.sigar.OperatingSystem;
import org.hyperic.sigar.Sigar;
import org.hyperic.sigar.SigarException;
import org.hyperic.sigar.Who;

/**
 *
 * @author MacaZekoMiš
 */
public class BashPanel extends javax.swing.JPanel {

    /**
     * Creates new form BashPanel
     */
     private JPanel pnlSadrzajko;
 private JPanel pnlVrijemeApi;
 private JPanel pnlProjekti;
    public BashPanel() throws IOException {
         initComponents();
       
        pnlProjekti = new ProjektiPanel();
        pnlVrijemeApi = new VrijemePanel();
        getCpuTotal();
      
        platform.setText(getPlatformName().toString());

        testGetOSInfo();
        
        testWho();
        change_Lbl.setVisible(false);
        jtxa.setLineWrap(true);
        jtxa.setWrapStyleWord(true);
        jtxa.setText("");
       JTextArea jtxa = new JTextArea();
       jtxa.setOpaque(false);
    }
 final static String newline = "\n";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void getCpuTotal() {
        Sigar sigar = new Sigar();
        CpuInfo[] infos;
        try {
            infos = sigar.getCpuInfoList();
            for (int i = 0; i < infos.length; i++) {// 不管是单块CPU还是多CPU都适用
                CpuInfo info = infos[i];
//				System.out.println("Mhz:" + info.getMhz());// CPU的总量MHz
//                mhz_InfoL.setText("Mhz: " + info.getMhz());
//				System.out.println("Vendor：" + info.getVendor());// 获得CPU的卖主，如：Intel
//                vendor_InfoL.setText("Proizvođač: " + info.getVendor());
//				System.out.println("Model：" + info.getModel());// 获得CPU的类别，如：Celeron
//                cpu_InfoL_3.setText("Model: " + info.getModel());
//				System.out.println("Cache Size：" + info.getCacheSize());// 缓冲存储器数量
                System.out.println("**************");
                 System.out.println("**************");
            }
            
        } catch (SigarException e) {
            e.printStackTrace();
        }
    }

    public String getPlatformName() {
        String hostname = "";
        try {
            hostname = InetAddress.getLocalHost().getHostName();
        } catch (Exception exc) {
            Sigar sigar = new Sigar();
            try {
                hostname = sigar.getNetInfo().getHostName();
            } catch (SigarException e) {
                hostname = "localhost.unknown";
            } finally {
                sigar.close();
            }
        }
        return hostname;
    }

    public void testGetOSInfo() {
        OperatingSystem OS = OperatingSystem.getInstance();
//
//        os_Info1_4.setText("Arhitektura: " + OS.getArch());
//
//        os_Info2_2.setText("Proizvođač: " + OS.getVendor());
//
//        os_Info3.setText("Verzija: " + OS.getVersion());
    }
    
     public void testWho() {
        try {
            Sigar sigar = new Sigar();
            Who[] who = sigar.getWhoList();
            if (who != null && who.length > 0) {
                for (int i = 0; i < who.length; i++) {
                    System.out.println("\n~~~~~~~~~" + String.valueOf(i) + "~~~~~~~~~");
                    Who _who = who[i];
//					System.out.println("获取设备getDevice() = " + _who.getDevice());
//					System.out.println("获得主机getHost() = " + _who.getHost());
//					System.out.println("获取的时间getTime() = " + _who.getTime());
                    // 当前系统进程表中的用户名
//					System.out.println("获取用户getUser() = " + _who.getUser());
                    if (i == 3) {
//                        platformU_label.setText(_who.getUser().toString());
                        platfore_console.setText(_who.getUser().toString() + " : ");

                    }

                }
            }
        } catch (SigarException e) {
            e.printStackTrace();
        }
    }

    public String getDefaultIpAddress() {
        String address = null;
        try {
            address = InetAddress.getLocalHost().getHostAddress();
            // 没有出现异常而正常当取到的IP时，如果取到的不是网卡循回地址时就返回
            // 否则再通过Sigar工具包中的方法来获取
            if (!NetFlags.LOOPBACK_ADDRESS.equals(address)) {
                return address;
            }
        } catch (UnknownHostException e) {
            // hostname not in DNS or /etc/hosts
        }
        Sigar sigar = new Sigar();
        try {
            address = sigar.getNetInterfaceConfig().getAddress();
        } catch (SigarException e) {
            address = NetFlags.LOOPBACK_ADDRESS;
        } finally {
            sigar.close();
        }
        return address;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        platform = new javax.swing.JLabel();
        change_Lbl = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxa = new javax.swing.JTextArea();
        platfore_console = new javax.swing.JLabel();
        jXMonthView1 = new org.jdesktop.swingx.JXMonthView();

        jcMousePanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jcMousePanel1.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMakr_7NDJfO.png"))); // NOI18N
        jcMousePanel1.setModo(6);
        jcMousePanel1.setmosaico(true);
        jcMousePanel1.setVisibleLogo(false);

        platform.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        platform.setForeground(new java.awt.Color(255, 255, 255));

        change_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        change_Lbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                change_LblPropertyChange(evt);
            }
        });

        textField1.setBackground(new java.awt.Color(0, 51, 51));
        textField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField1.setForeground(new java.awt.Color(0, 204, 254));
        textField1.setText("Enter command");
        textField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textField1FocusGained(evt);
            }
        });
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        textField1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField1TextValueChanged(evt);
            }
        });
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField1KeyReleased(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jtxa.setEditable(false);
        jtxa.setBackground(new java.awt.Color(0, 51, 51));
        jtxa.setColumns(20);
        jtxa.setForeground(new java.awt.Color(0, 204, 204));
        jtxa.setRows(5);
        jtxa.setBorder(null);
        jtxa.setFocusable(false);
        jScrollPane1.setViewportView(jtxa);

        platfore_console.setBackground(new java.awt.Color(0, 51, 51));
        platfore_console.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        platfore_console.setForeground(new java.awt.Color(0, 204, 255));
        platfore_console.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        platfore_console.setText(" :");
        platfore_console.setOpaque(true);

        jXMonthView1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(change_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(platfore_console, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jXMonthView1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(jXMonthView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(change_Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(platfore_console, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
//  private void postaviPanel(JPanel panel) {
//        pnlCmd.removeAll();
//        pnlCmd.add(panel);
//        panel.setSize(pnlCmd.getSize());
//        pnlCmd.revalidate();
//        pnlCmd.repaint();
//
//    }
    private void textField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField1FocusGained
        textField1.setText("");
    }//GEN-LAST:event_textField1FocusGained

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed

    }//GEN-LAST:event_textField1ActionPerformed

    private void textField1TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField1TextValueChanged

    }//GEN-LAST:event_textField1TextValueChanged

    private void textField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyPressed

    }//GEN-LAST:event_textField1KeyPressed

    private void textField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyReleased
        String text = textField1.getText();
        //        System.out.println(textField1.getText());
        System.out.println("uneseno je:" + text);

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            System.out.println("textjeee:" + text);
            change_Lbl.setText(textField1.getText());

        }
    }//GEN-LAST:event_textField1KeyReleased

    private void change_LblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_change_LblPropertyChange

        System.out.println("hhov famovzni text je:" + change_Lbl.getText());
        if (change_Lbl.getText().equalsIgnoreCase("IP")) {
            jtxa.setText(getDefaultIpAddress());
           
            
           
        } 
        
        else if (change_Lbl.getText().equalsIgnoreCase("vrijeme>gui")) {
            
//            
//           postaviPanel(pnlVrijemeApi);
         
        } 
            else if (change_Lbl.getText().equalsIgnoreCase("projekti>gui")) {
            
            
         
         
        } 
        
        
        
        else {
         
            
            jtxa.setText("\"" + change_Lbl.getText() + "\" " + " nije prepoznata kao unutarnja naredba. Ukucaj HELP za sve naredbe.");

        }

        if (change_Lbl.getText().equalsIgnoreCase("help")) {
         
            jtxa.setText("IP  --- Prikaži IP adresu"+newline+"VRIJEME --- Prikaži vrijeme u Osijeku"+newline+"VRIJEME>GUI --- Prikaži gui Vremena" + newline + "Help --- Prikaži sve naredbe");
        }
    }//GEN-LAST:event_change_LblPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel change_Lbl;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXMonthView jXMonthView1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTextArea jtxa;
    private javax.swing.JLabel platfore_console;
    private javax.swing.JLabel platform;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
