/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glavacevic.view;

import glavacevic.model.Operater;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.TimerTask;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import keeptoo.Drag;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author domagoj
 */
public class LoginForma extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public LoginForma() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_pozadinskiPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        loginn = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_password = new javax.swing.JPasswordField();
        loader = new javax.swing.JPanel();
        img_loader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        login_pozadinskiPanel.setBackground(new java.awt.Color(255, 255, 255));
        login_pozadinskiPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                login_pozadinskiPanelMouseDragged(evt);
            }
        });
        login_pozadinskiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_pozadinskiPanelMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        loginn.setBackground(new java.awt.Color(255, 255, 255));
        loginn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                loginnAncestorRemoved(evt);
            }
        });
        loginn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginnKeyPressed(evt);
            }
        });
        loginn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setText("admin@gmail.com");
        txt_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });
        loginn.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 186, 204, -1));

        jSeparator1.setForeground(new java.awt.Color(69, 202, 255));
        loginn.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 206, 204, -1));

        btn_login.setBackground(new java.awt.Color(69, 202, 255));
        btn_login.setForeground(java.awt.Color.white);
        btn_login.setText("Login");
        btn_login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_loginMousePressed(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        loginn.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 361, 89, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key-4-16.png"))); // NOI18N
        loginn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 246, -1, 24));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-16 (1).png"))); // NOI18N
        loginn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 178, -1, 30));

        jLabel4.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.darkGray);
        jLabel4.setText("Login");
        loginn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 41, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(69, 202, 255));
        loginn.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 270, 204, -1));

        txt_password.setText("t");
        txt_password.setBorder(null);
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        loginn.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 250, 204, 20));

        jPanel1.add(loginn, "card2");

        loader.setBackground(new java.awt.Color(255, 255, 255));
        loader.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                loaderAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                loaderAncestorRemoved(evt);
            }
        });

        img_loader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loader_backinout.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(69, 202, 255));
        jLabel1.setText("LOGGING IN");

        javax.swing.GroupLayout loaderLayout = new javax.swing.GroupLayout(loader);
        loader.setLayout(loaderLayout);
        loaderLayout.setHorizontalGroup(
            loaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loaderLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(img_loader, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        loaderLayout.setVerticalGroup(
            loaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loaderLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(img_loader, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        jPanel1.add(loader, "card3");

        javax.swing.GroupLayout login_pozadinskiPanelLayout = new javax.swing.GroupLayout(login_pozadinskiPanel);
        login_pozadinskiPanel.setLayout(login_pozadinskiPanelLayout);
        login_pozadinskiPanelLayout.setHorizontalGroup(
            login_pozadinskiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        login_pozadinskiPanelLayout.setVerticalGroup(
            login_pozadinskiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pozadinskiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pozadinskiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(888, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private void playSound() {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/sounds/bleep16pcm.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
//        txt_username.setText("");

//         new AePlayWav("bleep16pcm.wav").start();

    }//GEN-LAST:event_txt_usernameFocusGained

    private void LoginAkcija() {

        Operater o = glavacevic.pomocno.Autorizacija.autoriziraj(txt_username.getText(), txt_password.getPassword());
        if (o == null) {
            JOptionPane.showMessageDialog(getRootPane(), "Neispravna kombinacija korisničkog imena i lozinke");
            oznaciGresku(txt_password);
            oznaciGresku(txt_username);
        } else {
            new FramePostavke(o).setVisible(true);
            dispose();
        }

    }
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        //stariji nacin bez hibernat-a
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//
//        try {
//            Connection veza = DriverManager.getConnection("jdbc:mysql://localhost/technoj18?"
//                    + "user=root&password=&serverTimezone=CET&useSSL=true");
//            PreparedStatement izraz = veza.prepareStatement("select * from operater where email = ? and password = ?");
//            izraz.setString(1, txt_username.getText());
//            izraz.setString(2, txt_password.getText());
//            ResultSet rs = izraz.executeQuery();
//
//            if (rs.next()) {
//                
//                loader.show();
//                loginn.hide();
//
//                new java.util.Timer().schedule(new TimerTask() {
//                    @Override
//                    public void run() {
//                        Main m = new Main();
//                        m.setExtendedState(MAXIMIZED_BOTH);
//                        m.show();
//
//                        dispose();
//                    }
//                }, 1000 * 5);
//            } else {
//                JOptionPane.showMessageDialog(null, "Username or Password are not correct.");
//                txt_username.setText("");
//                txt_password.setText("");
//                new AePlayWav("bleep16pcm.wav").start();
//
//            }
//
//            rs.close();
//            izraz.close();
//            veza.close();
//
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }     
        LoginAkcija();

    }//GEN-LAST:event_btn_loginActionPerformed

    private void oznaciGresku(JTextField polje) {
        polje.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000")));
        polje.requestFocus();
    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void loaderAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_loaderAncestorRemoved
        InputStream music;
        try {
            music = new FileInputStream(new File("src/sounds/ReReversed.wav"));
            AudioStream audios = new AudioStream(music);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_loaderAncestorRemoved

    private void loaderAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_loaderAncestorMoved

    }//GEN-LAST:event_loaderAncestorMoved

    private void loginnAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_loginnAncestorRemoved
        InputStream music;
        try {
            music = new FileInputStream(new File("src/sounds/LoadingSoundwithTransient.wav"));
            AudioStream audios = new AudioStream(music);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_loginnAncestorRemoved

    private void btn_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMousePressed
//         new AePlayWav("bleep16pcm.wav").start();
    }//GEN-LAST:event_btn_loginMousePressed

    private void loginnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginnKeyPressed

        
    }//GEN-LAST:event_loginnKeyPressed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed

    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LoginAkcija();

        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void login_pozadinskiPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_pozadinskiPanelMouseDragged
     
        
        new Drag(login_pozadinskiPanel).moveWindow(evt);
    }//GEN-LAST:event_login_pozadinskiPanelMouseDragged

    private void login_pozadinskiPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_pozadinskiPanelMousePressed
      new Drag(login_pozadinskiPanel).onPress(evt);
    }//GEN-LAST:event_login_pozadinskiPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel img_loader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel loader;
    private javax.swing.JPanel login_pozadinskiPanel;
    private javax.swing.JPanel loginn;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
