/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glavacevic.view;
import glavacevic.postavke.PostaviIzgled;
import glavacevic.postavke.Postavke;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JPanel;
import glavacevic.view.FramePostavke;
import static glavacevic.postavke.Postavke.postavke;

/**
 *
 * @author MacaZekoMiš
 */
public class PostavkePanel extends javax.swing.JPanel {
 Postavke P ;
// 

    /**
     * Creates new form PostavkePanel
     */
    public PostavkePanel() {
        initComponents();
         setName("Postavke");
     
           P = new Postavke();
            PostaviIzgled cf = new PostaviIzgled();
           cf.PostaviIzgled();
         
         
         
    } 
    

   
    
    
    
     AnimationClass AC = new AnimationClass();
     AnimationClass sat = new AnimationClass();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_dot1 = new javax.swing.JLabel();
        okrug1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_dot2 = new javax.swing.JLabel();
        okrug2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_dot3 = new javax.swing.JLabel();
        okrug3 = new javax.swing.JLabel();

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Change application theme ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dark theme");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Snow theme");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sea theme");

        jPanel7.setOpaque(false);
        jPanel7.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel4MouseReleased(evt);
            }
        });
        jPanel4.setLayout(null);

        lbl_dot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dot.png"))); // NOI18N
        jPanel4.add(lbl_dot1);
        lbl_dot1.setBounds(2, 10, 11, 10);

        okrug1.setBackground(new java.awt.Color(255, 255, 255));
        okrug1.setForeground(new java.awt.Color(51, 51, 0));
        okrug1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/withoutdot.png"))); // NOI18N
        jPanel4.add(okrug1);
        okrug1.setBounds(2, 0, 30, 30);

        jPanel7.add(jPanel4);
        jPanel4.setBounds(0, 11, 29, 28);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel5MouseReleased(evt);
            }
        });
        jPanel5.setLayout(null);

        lbl_dot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dot.png"))); // NOI18N
        jPanel5.add(lbl_dot2);
        lbl_dot2.setBounds(2, 10, 11, 10);

        okrug2.setBackground(new java.awt.Color(255, 255, 255));
        okrug2.setForeground(new java.awt.Color(51, 51, 0));
        okrug2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/withoutdot.png"))); // NOI18N
        jPanel5.add(okrug2);
        okrug2.setBounds(2, 0, 30, 30);

        jPanel7.add(jPanel5);
        jPanel5.setBounds(0, 45, 29, 28);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel6MouseReleased(evt);
            }
        });
        jPanel6.setLayout(null);

        lbl_dot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dot.png"))); // NOI18N
        jPanel6.add(lbl_dot3);
        lbl_dot3.setBounds(2, 10, 11, 10);

        okrug3.setBackground(new java.awt.Color(255, 255, 255));
        okrug3.setForeground(new java.awt.Color(51, 51, 0));
        okrug3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/withoutdot.png"))); // NOI18N
        jPanel6.add(okrug3);
        okrug3.setBounds(2, 0, 30, 30);

        jPanel7.add(jPanel6);
        jPanel6.setBounds(0, 79, 29, 28);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MousePressed
 Boolean hidden = false;
    double location = 0;
    String pozicija = "";
    String store = "0,153,255";

         

     
    Color Startcolor = new Color(0,153,255);
    Color Endcolor = new Color(51,51,255);
     int StartcolorInt = Startcolor.getRGB();
      int EndcolorInt = Endcolor.getRGB();
//    
    void snow (){
        FramePostavke.MotherBoard.setkStartColor(new java.awt.Color(158,158,158));
         FramePostavke.MotherBoard.setkEndColor(new java.awt.Color(158,158,158));


//     
    }
    
    void sea(){
                 FramePostavke.MotherBoard.setkStartColor(new java.awt.Color(51,102,255));
                 FramePostavke.MotherBoard.setkEndColor(new java.awt.Color(0,204,255));


    }
    
    void dark(){
        
    FramePostavke.MotherBoard.setkStartColor(new java.awt.Color(0,0,0));   
    FramePostavke.MotherBoard.setkEndColor(new java.awt.Color(0,18,51));

    }
    
    void mainTheme(){
         FramePostavke.MotherBoard.setkStartColor(new java.awt.Color(255,0,255));
         FramePostavke.MotherBoard.setkEndColor(new java.awt.Color(0,0,255));

    }
    
    
    
//    
//    public void printName(String RecievedName){
//        System.out.println("You entered: " + RecievedName);
//}
    
    
      
    
    
    private void jPanel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseReleased
        
        AC.jLabelXRight(2, 8, 10, 1, lbl_dot1);
        AC.jLabelXLeft(8, 2, 10, 1, lbl_dot1);

        Point gtz1 = lbl_dot1.getLocation();
        location = gtz1.getLocation().getX();

        if(location == 2){
         
            snow ();
            String pozicija = "Dvica";
        }if(location == 8){
            String pozicija = "Osmica";
            mainTheme();
        }
        if (location == 8 && !Entered) {
            //            System.err.println("DOBILI SMO OSMICU");
            //            ImageIcon II = new ImageIcon(getClass().getResource("/images/withoutdot.png"));

            //       s
        }
        if (!Entered && location == 2) {
            //            System.err.println("DOBILI SMO DVA");
            //            ImageIcon III = new ImageIcon(getClass().getResource("/images/withoutdotU.png"));
            //
            //            okrug.setIcon(III);

        }

        P.SpremiPostavku("1");

        FramePostavke.MotherBoard.revalidate();
        FramePostavke.MotherBoard.repaint();
    }//GEN-LAST:event_jPanel4MouseReleased
Boolean Entered = false;
    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseReleased

        AC.jLabelXRight(2, 8, 10, 1, lbl_dot2);
        AC.jLabelXLeft(8, 2, 10, 1, lbl_dot2);

        Point gtz2 = lbl_dot2.getLocation();
        location = gtz2.getLocation().getX();

        if(location == 2){

            sea ();
            String pozicija = "Dvica";
        }if(location == 8){
            String pozicija = "Osmica";
            mainTheme();
        }

        FramePostavke.MotherBoard.revalidate();
        FramePostavke.MotherBoard.repaint();
        
        P.SpremiPostavku("2");
        ;

    }//GEN-LAST:event_jPanel5MouseReleased

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseReleased

        AC.jLabelXRight(2, 8, 10, 1, lbl_dot3);

        AC.jLabelXLeft(8, 2, 10, 1, lbl_dot3);
        Point gtz3 = lbl_dot3.getLocation();
        location = gtz3.getLocation().getX();
        if(location == 2){
            dark();
            String pozicija = "Dvica";
        }if(location == 8){
            String pozicija = "Osmica";
            mainTheme();
        }
//
        FramePostavke.MotherBoard.revalidate();
        FramePostavke.MotherBoard.repaint();
        P.SpremiPostavku("3");
    }//GEN-LAST:event_jPanel6MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_dot1;
    private javax.swing.JLabel lbl_dot2;
    private javax.swing.JLabel lbl_dot3;
    private javax.swing.JLabel okrug1;
    private javax.swing.JLabel okrug2;
    private javax.swing.JLabel okrug3;
    // End of variables declaration//GEN-END:variables
}
