/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glavacevic.view;

import glavacevic.controller.ObradaProjekt;
import glavacevic.pomocno.SpremiSliku;
import glavacevic.model.Artist;
import glavacevic.model.Projekt;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jcMousePanel.jcMousePanel;
import glavacevic.view.OpacityPanel;
import glavacevic.pomocno.EdunovaException;
import java.awt.Component;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author MacaZekoMiš
 */
public class ProjektiPanel extends jcMousePanel {

    /**
     * Creates new form ProjektiPanel
     */
    
    private JPanel pnlArtist;
    private JPanel pnlDjelovi;
    private JPanel pnlProizvodac;
    private JPanel pnlGrupe;
    private JPanel pnlKupci;
    private ObradaProjekt o;
    final private DecimalFormat df;
    String putanja = System.getProperty("user.dir");
    private keeptoo.KGradientPanel mali;
    private Projekt projekt;

    public ProjektiPanel() {    
       
        initComponents();
        pnlDjelovi = new VoziloPanel();
        pnlProizvodac = new ProizvodacPanel();
        pnlArtist = new ArtistiPanel();
        pnlGrupe = new GrupeKPanel();
        pnlKupci = new NarudzbePanel();
        this.setModo(2);
        this.setVisibleLogo(false);
        setName("Projekti");
        o = new ObradaProjekt();
    ucitajProjekte();
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("hr", "HR"));
        df = (DecimalFormat) nf;
        df.applyPattern("###,##0.00");

//         
//         tPane.add("", tab2Icon,pnlArtist);
//       
        tPane.addTab("", tab1Icon, pnlArtist);
        tPane.addTab("", tab1Icon, pnlArtist);
        tPane.addTab("", tab4Icon, pnlProizvodac);
        tPane.addTab("", tab3Icon, pnlGrupe);
        tPane.addTab("", tab5Icon, pnlDjelovi);
        tPane.addTab("", tab6Icon, pnlKupci);
          
//        
//        pane.setOpaque(false);
//     
//        pane.setBackground(Color.red);
    }

    ImageIcon tab1Icon = new ImageIcon(
            this.getClass().getResource("/images/icons8_Employee_24px.png"));
    ImageIcon tab2Icon = new ImageIcon(
            this.getClass().getResource("/images/database-16.png"));
     ImageIcon tab3Icon = new ImageIcon(
            this.getClass().getResource("/images/icons8_User_Groups_24px.png"));
  ImageIcon tab4Icon = new ImageIcon(
            this.getClass().getResource("/images/icons8_Manager_24px.png"));
    ImageIcon tab5Icon = new ImageIcon(
            this.getClass().getResource("/images/icons8_Car_24px.png"));
    ImageIcon tab6Icon = new ImageIcon(
            this.getClass().getResource("/images/icons8_Shopping_Cart_24px.png"));


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPane = new javax.swing.JTabbedPane();
        pnlPodaci = new keeptoo.KGradientPanel();
        kButton1 = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnDodajNovi = new javax.swing.JButton();
        btnPromjena = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        txtDirektorij = new javax.swing.JLabel();
        btn_slika1 = new javax.swing.JButton();
        lbl_img1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProjekt = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtUvjet = new javax.swing.JTextField();
        txtProjekt = new javax.swing.JTextField();
        txtCijena = new javax.swing.JTextField();
        txtTrajanje = new javax.swing.JTextField();

        setModo(6);
        setOpaque(false);
        setVisibleLogo(false);

        tPane.setBackground(new java.awt.Color(51, 51, 51));
        tPane.setOpaque(true);
        tPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tPaneStateChanged(evt);
            }
        });

        pnlPodaci.setkEndColor(new java.awt.Color(51, 51, 51));
        pnlPodaci.setkStartColor(new java.awt.Color(102, 102, 102));

        kButton1.setBorder(null);
        kButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-list-24.png"))); // NOI18N
        kButton1.setText("Dodaj novi projekt");
        kButton1.setBorderPainted(false);
        kButton1.setFocusPainted(false);
        kButton1.setFocusable(false);
        kButton1.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton1.setkHoverColor(new java.awt.Color(0, 102, 153));
        kButton1.setkHoverEndColor(new java.awt.Color(51, 0, 255));
        kButton1.setkStartColor(new java.awt.Color(102, 102, 102));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Naziv");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Cijena");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Trajanje");

        btnDodajNovi.setBackground(new java.awt.Color(0, 0, 0));
        btnDodajNovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-file-24.png"))); // NOI18N
        btnDodajNovi.setOpaque(false);
        btnDodajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNoviActionPerformed(evt);
            }
        });

        btnPromjena.setBackground(new java.awt.Color(0, 0, 0));
        btnPromjena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Change_24px.png"))); // NOI18N
        btnPromjena.setOpaque(false);
        btnPromjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjenaActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(0, 0, 0));
        btnObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_Bin_24px.png"))); // NOI18N
        btnObrisi.setOpaque(false);
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        txtDirektorij.setBackground(new java.awt.Color(255, 255, 255));
        txtDirektorij.setOpaque(true);

        btn_slika1.setBackground(new java.awt.Color(69, 202, 255));
        btn_slika1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloud-upload-16.png"))); // NOI18N
        btn_slika1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_slika1ActionPerformed(evt);
            }
        });

        lbl_img1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Launchpad_96px.png"))); // NOI18N

        lstProjekt.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstProjekt.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProjektValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstProjekt);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Search_24px.png"))); // NOI18N

        javax.swing.GroupLayout pnlPodaciLayout = new javax.swing.GroupLayout(pnlPodaci);
        pnlPodaci.setLayout(pnlPodaciLayout);
        pnlPodaciLayout.setHorizontalGroup(
            pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtProjekt)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                    .addComponent(jLabel31)
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addComponent(btnDodajNovi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromjena, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPodaciLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(txtDirektorij, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_img1)))
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btn_slika1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPodaciLayout.setVerticalGroup(
            pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPodaciLayout.createSequentialGroup()
                                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(11, 11, 11)
                                .addComponent(txtProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31))
                            .addGroup(pnlPodaciLayout.createSequentialGroup()
                                .addComponent(lbl_img1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_slika1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPodaciLayout.createSequentialGroup()
                                .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDirektorij, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPromjena)
                    .addComponent(btnDodajNovi)
                    .addComponent(btnObrisi))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        tPane.addTab("Projekt", pnlPodaci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tPane, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tPane, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstProjektValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProjektValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        projekt = lstProjekt.getSelectedValue();
        if (projekt == null) {
            return;
        }
         ocistiPolja();
        String filename = null;
        txtProjekt.setText(projekt.getNaziv());
        txtTrajanje.setText(String.valueOf(projekt.getTrajanje()));
        txtCijena.setText(df.format(projekt.getCijena()));
        txtDirektorij.setText(projekt.getDirektorij());
        filename = putanja + projekt.getDirektorij();
          if(projekt.getDirektorij()==null || projekt.getDirektorij().isEmpty()){
          lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Male_User_96px_1.png"))); 
        }else{
               ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_SMOOTH));
        System.out.println("FILENAME JESAD : " + filename + "s.getOstalo je : " + projekt.getDirektorij());
        lbl_img1.setIcon(imageIcon);
          }
       
    }//GEN-LAST:event_lstProjektValueChanged

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        projekt = lstProjekt.getSelectedValue();
        if (projekt == null) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberi smjer");
            return;
        }

        o.obrisi(projekt);
        ucitajProjekte();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPromjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjenaActionPerformed
        projekt = lstProjekt.getSelectedValue();
        if (projekt == null) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberi smjer");
            return;
        }

        if (!popuniSvojstva()) {
            return;
        }

        try {
            o.promjena(projekt);
            ucitajProjekte();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
        }
    }//GEN-LAST:event_btnPromjenaActionPerformed

    private void btnDodajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNoviActionPerformed

        projekt = new Projekt();

        if (!popuniSvojstva()) {
            return;
        }
        try {
            o.dodaj(projekt);
            ucitajProjekte();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajNoviActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void btn_slika1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_slika1ActionPerformed
        String filename = null;

        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG, GIF, and PNG Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            System.out.println("You chose to open this file: "
                + file.getName());
            BufferedImage image;
            try {
                image = ImageIO.read(file);

                ImageIO.write(image, "jpg", new File(putanja + file.getName()));
            } catch (IOException ex) {
                Logger.getLogger(SpremiSliku.class.getName()).log(Level.SEVERE, null, ex);
            }

            //       chooser.showOpenDialog(null);
            //       File f = chooser.getSelectedFile();
            filename = file.getAbsolutePath();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_SMOOTH));
            lbl_img1.setIcon(imageIcon);
            //            lbl_dirOdabrane.setText(filename);
            txtDirektorij.setText(file.getName());

        }
    }//GEN-LAST:event_btn_slika1ActionPerformed

    private void tPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tPaneStateChanged
        System.out.println("Tab: " + tPane.getSelectedIndex());
        if(tPane.getSelectedIndex()==0){
             
       
             
        }else if (tPane.getSelectedIndex()==1){
       
               
           
          
               
        }
    }//GEN-LAST:event_tPaneStateChanged

    
    
     
    private void ucitajProjekte() {

        DefaultListModel<Projekt> m = new DefaultListModel<>();
        o.getEntiteti(txtUvjet.getText()).forEach((p) -> {
            m.addElement(p);
        });
        lstProjekt.setModel(m);
    }

    private void ocistiPolja() {

        for (Component c : pnlPodaci.getComponents()) {
            if (c instanceof JTextField) {
                ((JTextField) c).setText("");
            }
        }
    }

    private boolean popuniSvojstva() {
        projekt.setNaziv(txtProjekt.getText());
        
        if(projekt.getDirektorij()==null || projekt.getDirektorij().isEmpty()){
//            JOptionPane.showMessageDialog(getRootPane(), "majketi di ces bez slike");
//            return false;
 projekt.setDirektorij(txtDirektorij.getText());
        }
        else { 
            projekt.setDirektorij(txtDirektorij.getText());
            
        }
       
        
        try {
            projekt.setTrajanje(Integer.parseInt(txtTrajanje.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), "Trajanje obavezno cijeli broj");
            return false;
        }

        try {
            projekt.setCijena(new BigDecimal(df.parse(txtCijena.getText()).doubleValue()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), "Cijena mora biti broj");
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNovi;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjena;
    private javax.swing.JButton btn_slika1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KButton kButton1;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JList<Projekt> lstProjekt;
    private keeptoo.KGradientPanel pnlPodaci;
    private javax.swing.JTabbedPane tPane;
    private javax.swing.JTextField txtCijena;
    private javax.swing.JLabel txtDirektorij;
    private javax.swing.JTextField txtProjekt;
    private javax.swing.JTextField txtTrajanje;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables
}
