/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glavacevic.view;

/**
 *
 * @author MacaZekoMiš
 */


import glavacevic.model.Grupa;
import static glavacevic.pomocno.HibernateUtil.getSession;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtilities;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;
import static glavacevic.view.FramePostavke.pnlSadrzaj;
import java.awt.Component;
import javax.swing.JComponent;
import javax.swing.RepaintManager;
import jcMousePanel.jcMousePanel;
import org.pushingpixels.trident.Timeline;
public class StatistikePanel  extends jcMousePanel{

    /**
     * Creates new form StatistikePanel
     */
    

     
    
    public StatistikePanel() {
        
       this.setModo(6);
       this.setOpaque(true);
       this.setVisibleLogo(false);
       initComponents();
         setName("Statistike");
//         repaint();
//          RenderChart();
          


    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        
Color trans = new Color(0xFF, 0xFF, 0xFF, 0);

    
    private PieDataset createDataset( ) {
    
      DefaultPieDataset dataset = new DefaultPieDataset( );
       int brojZaposlenika = ((Long)getSession().createQuery("select count(*) from Zaposlenik").uniqueResult()).intValue();
        System.out.println(brojZaposlenika);
      dataset.setValue( "Broj Zaposlenika" , new Double( brojZaposlenika ) );  
      dataset.setValue( "1" , new Double( 20 ) );   
      dataset.setValue( "2" , new Double( 40 ) );    
      dataset.setValue( "3" , new Double( 10 ) );  
      return dataset;         
   }
    
    
    void createDataset( PieDataset dataset ) {
      JFreeChart chart = ChartFactory.createPieChart(      
         "Sales",   // chart title 
         dataset,          // data    
         true,             // include legend   
         true, 
         false);
   }
    
        void RenderChart() {
         this.repaint();
            PieDataset ds = createDataset();
        JFreeChart chart = ChartFactory.createPieChart("",ds);
            
        
        ChartPanel cp = new ChartPanel(chart);

      chart.setBackgroundPaint(getForeground());
//      cp.setOpaque(false);
      
        chart.getPlot().setBackgroundPaint(new Color(255,255,255,0)); 
      
        pnlChartData.add(cp);


    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChartData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        pnlChartData.setOpaque(false);
        pnlChartData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlChartDataMousePressed(evt);
            }
        });
        pnlChartData.setLayout(new java.awt.CardLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Statistike ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(pnlChartData, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlChartData, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
              RenderChart(); 
           
    }//GEN-LAST:event_formAncestorAdded

    private void pnlChartDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChartDataMousePressed

    }//GEN-LAST:event_pnlChartDataMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlChartData;
    // End of variables declaration//GEN-END:variables
}
